name: Run Jenkinsfile via Jenkinsfile Runner

on:
  schedule:
    - cron: '0 0 * * *' # every day
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - crowdsec

jobs:
  jenkins-run:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/jenkinsci/jenkinsfile-runner:master
    steps:
      - uses: actions/setup-node@v3
      - name: Update system
        run: |
            apt-get update
            apt-get upgrade

    #   - name: install nodejs20glibc2.17
    #     run: |
    #         apt install curl -y
    #         curl -LO https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-linux-x64-glibc-217.tar.xz
    #         tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
    #         ldd /__e/node20/bin/node
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Run Jenkinsfile
        uses: jenkinsci/jfr-container-action@master
        with:
          command: run
          jenkinsfile: .jenkins/Jenkinsfile